name: Compile Docker Images

on: [push]

jobs:
  rust-compile:
    name: Build gateway-mfr-rs
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Clone repo
        run: |
          git clone --branch v0.1.3 https://github.com/helium/gateway-mfr-rs.git .

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check

      - name: Build gateway-mfr-rs
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release

      - name: Copy release file
        run: |
          cp ./target/aarch64-unknown-linux-musl/release/gateway_mfr gateway_mfr

      - uses: actions/upload-artifact@v2
        with:
          name: gateway_mfr
          path: ./gateway_mfr

  main:
    runs-on: ubuntu-20.04
    needs: [rust-compile]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: gateway_mfr
          path: ./gateway_mfr

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
                nebraltd/hm-diag:${{ github.sha }}
                nebraltd/hm-diag:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
